TASK_ERROR_CODE = 404
TASK_SUCCESS_CODE = 200
RESPONSE_STATUS_CODE_SUCCESS = 200
RESPONSE_STATUS_CODE_ERROR = 404
RESPONSE_AUTH_CODE_ERROR = 401
RESPONSE_ALLOW_CODE_ERROR = 403
DEFAULT_PERMISSIONS = ['login', 'logout', 'mesh_query', 'get_task_status']

